apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    scraper: tiingo
    volume.beta.kubernetes.io/storage-provisioner: storageos
  name: tiingo-pvc
  namespace: scraper
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: retained
  volumeMode: Filesystem

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    scraper: cboe
    volume.beta.kubernetes.io/storage-provisioner: storageos
  name: cboe-pvc
  namespace: scraper
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: retained
  volumeMode: Filesystem
