apiVersion: v1
kind: ServiceAccount
metadata:
  name: scraper-cleanup
  namespace: scraper

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: scraper-cleanup
  namespace: scraper
rules:
  - apiGroups: ["extensions", "batch"]
    resources: ["deployments", "jobs"]
    verbs: ["get", "list", "patch", "update", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: scraper-cleanup
  namespace: scraper
subjects:
  - kind: ServiceAccount
    name: scraper-cleanup
    namespace: scraper
roleRef:
  kind: ClusterRole
  name: scraper-cleanup
  apiGroup: rbac.authorization.k8s.io
